spring:
  application:
    name: study-session-service
  datasource:
    url: jdbc:mysql://localhost:3308/commands_db
    username: root
    password: password123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  error:
    include-message: always

kafka:
  topic:
    commands: study-session-commands-topic
    study-sessions: study-sessions-topic