spring:
  datasource:
    url: jdbc:h2:mem:commands_db
    username: sa
    password:
      # Use H2 in-memory database for local development
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        trace: false
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect